jwtauth:
  password:
    encoder:
      secret: asewqeqs
      iteration: 33
      keylength: 256
  jjwt:
    secret: 2s5v8x/A?D(G+KbPeShVmYq3t6w9z$B&E)H@McQfTjWnZr4u7x!A%D*F-JaNdRgU
    expiration: 28880

spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always
server:
  port: 8082
